"use client";

import { useState } from "react";

export default function MorningDewSerum() {
  const [quantity, setQuantity] = useState(1);
  const [added, setAdded] = useState(false);
  return <main className="detail-page">
    <div className="announcement">Complimentary shipping on orders over $75 <span>•</span> A little glow, on us</div>
    <header><a className="wordmark" href="/"><span className="brand-symbol" aria-hidden="true"/>OLIVIA <em>GLOW</em></a><nav><a href="/shop">Shop</a><a href="/#rituals">Rituals</a><a href="/#story">Our story</a></nav><div className="actions"><a className="search" href="/shop" aria-label="Search">⌕</a><button className="account" aria-label="Account">◯</button><a className="bag" href="/shop">Bag</a></div></header>
    <div className="breadcrumbs"><a href="/">Home</a> / <a href="/shop">Shop</a> / Morning Dew Serum</div>
    <section className="product-detail"><div className="gallery"><div className="detail-product-image rose"><span className="product-label">NEW</span><div className="bottle b1 detail-bottle"><strong>OLIVIA</strong><span>GLOW</span><i>MORNING DEW<br/>SERUM</i></div></div><div className="detail-thumbnail peach"></div><div className="detail-thumbnail cream"></div></div><div className="detail-info"><p className="eyebrow">HYDRATE + BRIGHTEN</p><h1>Morning Dew<br/><i>Serum</i></h1><div className="rating">★★★★★ <span>4.9 (128 reviews)</span></div><p className="detail-price">$48.00 <small>30 ml / 1 fl. oz.</small></p><p className="description">A featherlight daily serum that cushions skin in lasting hydration and leaves a fresh, soft-focus glow.</p><div className="benefit-pills"><span>Fragrance free</span><span>Vegan</span><span>Dermatologist tested</span></div><div className="purchase-row"><div className="quantity"><button onClick={()=>setQuantity(Math.max(1, quantity-1))}>−</button><span>{quantity}</span><button onClick={()=>setQuantity(quantity+1)}>+</button></div><button className="button dark add-detail" onClick={()=>setAdded(true)}>{added ? "Added to bag ✓" : "Add to bag — $48.00"}</button></div><p className="shipping-note">Free shipping and returns on orders over $75.</p><details open><summary>Why you’ll love it <b>+</b></summary><p>Layers of hyaluronic acid draw in hydration while niacinamide helps visibly even tone and texture over time.</p></details><details><summary>How to use <b>+</b></summary><p>Press one to two pumps into clean, lightly damp skin before moisturizer, morning and evening.</p></details><details><summary>Full ingredients <b>+</b></summary><p>Aqua, glycerin, niacinamide, sodium hyaluronate, panthenol, and skin-loving botanical extracts.</p></details></div></section>
    <section className="routine"><p className="eyebrow">COMPLETE THE RITUAL</p><h2>Pairs beautifully <i>with.</i></h2><div className="routine-cards"><a href="/shop"><div className="mini-card peach"><div className="bottle b0"><strong>OLIVIA</strong><span>GLOW</span><i>CLEANSER</i></div></div><h3>Cloud Milk Cleanser</h3><span>$32.00</span></a><a href="/shop"><div className="mini-card cream"><div className="bottle b2"><strong>OLIVIA</strong><span>GLOW</span><i>CREAM</i></div></div><h3>Velvet Barrier Cream</h3><span>$42.00</span></a></div></section>
    <footer><div className="footer-brand"><a className="wordmark" href="/"><span className="brand-symbol" aria-hidden="true"/>OLIVIA <em>GLOW</em></a><p>Thoughtful skincare for your softest glow.</p></div><div><b>Shop</b><a href="/shop">Best sellers</a><a href="/shop">New arrivals</a></div><div><b>About</b><a href="/#story">Our story</a></div><div><b>Follow along</b><a href="#">Instagram</a></div><small>© 2026 Olivia Glow. Made with care.</small></footer>
  </main>;
}
