const orders = [
  ["#OG-1048", "Maya Rodriguez", "$126.00", "Paid", "Preparing"],
  ["#OG-1047", "Isabel Tan", "$48.00", "Paid", "Shipped"],
  ["#OG-1046", "Chloe Morgan", "$86.00", "Paid", "Delivered"],
  ["#OG-1045", "Sophia Lee", "$54.00", "Pending", "Awaiting payment"],
];

export default function Admin() {
  return <main className="admin-shell">
    <aside className="admin-sidebar"><a className="admin-brand" href="/"><span className="brand-symbol" aria-hidden="true"/>OLIVIA <em>GLOW</em></a><p className="admin-label">STORE MANAGEMENT</p><nav className="admin-nav"><a className="active" href="/admin">Overview</a><a href="/shop">Orders <span>8</span></a><a href="/shop">Products</a><a href="/shop">Inventory</a><a href="/shop">Customers</a><a href="/shop">Marketing</a><a href="/shop">Content</a><a href="/shop">Analytics</a></nav><div className="admin-user"><div>OC</div><p>Olivia Chen<small>Administrator</small></p><b>⌄</b></div></aside>
    <section className="admin-content"><header className="admin-header"><div><p className="eyebrow">TUESDAY, JULY 28</p><h1>Good morning, <i>Olivia.</i></h1></div><div className="admin-actions"><button aria-label="Notifications">♢</button><a href="/shop">View store ↗</a></div></header><section className="admin-stats"><article><p>NET SALES</p><h2>$12,840<span>↗ 18.2%</span></h2><small>vs. $10,864 last period</small></article><article><p>ORDERS</p><h2>284<span>↗ 12.4%</span></h2><small>vs. 253 last period</small></article><article><p>AVERAGE ORDER</p><h2>$45.21<span>↗ 5.8%</span></h2><small>vs. $42.73 last period</small></article><article><p>RETURNING RATE</p><h2>38.6%<span>↗ 2.1%</span></h2><small>Healthy repeat purchase rate</small></article></section><section className="admin-grid"><article className="sales-card"><div className="admin-card-title"><div><p className="eyebrow">SALES OVER TIME</p><h2>$48,294 <span>↗ 18.2%</span></h2></div><button>Last 30 days⌄</button></div><div className="chart"><i style={{height:"36%"}}/><i style={{height:"57%"}}/><i style={{height:"42%"}}/><i style={{height:"70%"}}/><i style={{height:"58%"}}/><i style={{height:"81%"}}/><i style={{height:"65%"}}/><i style={{height:"93%"}}/><i style={{height:"74%"}}/><i style={{height:"88%"}}/><i style={{height:"67%"}}/><i style={{height:"100%"}}/></div><div className="chart-labels"><span>JUL 1</span><span>JUL 10</span><span>JUL 20</span><span>TODAY</span></div></article><article className="stock-card"><p className="eyebrow">INVENTORY WATCH</p><h2>Low stock</h2><div><span>Cloud Milk Cleanser</span><b>7 left</b></div><div><span>Petal Soft Mist</span><b>12 left</b></div><div><span>Golden Hour Oil</span><b>16 left</b></div><a href="/shop">Manage inventory →</a></article></section><section className="orders-card"><div className="admin-card-title"><div><p className="eyebrow">ORDERS</p><h2>Recent orders</h2></div><a href="/shop">View all orders →</a></div><div className="order-table"><div className="order-row heading"><span>ORDER</span><span>CUSTOMER</span><span>TOTAL</span><span>PAYMENT</span><span>FULFILMENT</span></div>{orders.map(order=><div className="order-row" key={order[0]}><b>{order[0]}</b><span>{order[1]}</span><span>{order[2]}</span><em>{order[3]}</em><small>{order[4]}</small></div>)}</div></section></section>
  </main>;
}
